export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const CLEAR_FORM = "CLEAR_FORM";
export const HANDLE_FORM_CHANGE = "HANDLE_FORM_CHANGE";

export const TOGGLE_LOADING = "TOGGLE_LOADING";

export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const CREATE_QUIZ_SUCCESS = "CREATE_QUIZ_SUCCESS";

export const LOGOUT_USER = "LOGOUT_USER";
