export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const TOGGLE_LOADING = "TOGGLE_LOADING";

export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const LOGOUT_USER = "LOGOUT_USER";
